name: Unit Tests

on:

  push:
    branches: [main]
  pull_request:
    branches: [main]
    
   env:
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ variables.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ variables.STRIPE_SECRET_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{ variables.STRIPE_WEBHOOK_SECRET}}
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3

      

      - run: npm ci
      - run: npm test
      - run: npm run build
